#!/usr/bin/env bash
# smoke-alarm installer — make smoke-alarm usable by ANY agentic system, three ways:
#
#   1. CLI on PATH         `smoke-alarm grade <path>` from inside any project (universal)
#   2. Skill files         copied into each AI tool's skills dir (skill-aware agents)
#   3. PostToolUse hook     auto-grades on test writes (Claude Code, Codex)
#
#   ./install.sh            install (idempotent)
#   ./install.sh doctor     verify the install + dependencies
#   ./install.sh uninstall  remove everything it installed
#
# Only touches directories named `smoke-alarm` inside known roots. Never disturbs
# other skills, other CLIs, or unrelated config.

set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/skills/smoke-alarm"
SKILL="smoke-alarm"

# Canonical install location the PATH command points at — independent of any agent,
# so the CLI keeps working even if you move or delete the cloned repo.
LIB="$HOME/.local/share/smoke-alarm"
BIN_DIR="$HOME/.local/bin"
BIN="$BIN_DIR/smoke-alarm"

# Known per-tool skill roots. Missing ones are skipped, not created.
TOOL_ROOTS=(
  "$HOME/.claude/skills"
  "$HOME/.codex/skills"
  "$HOME/.cursor/skills"
  "$HOME/.config/agents/skills"
  "$HOME/.agents/skills"
)

c_red()  { printf '\033[31m%s\033[0m\n' "$*"; }
c_grn()  { printf '\033[32m%s\033[0m\n' "$*"; }
c_dim()  { printf '\033[2m%s\033[0m\n' "$*"; }

check_python() {
  if ! command -v python3 >/dev/null 2>&1; then
    c_red "python3 not found — smoke-alarm's instruments need Python >= 3.11 (tomllib)."
    return 1
  fi
  local v; v="$(python3 -c 'import sys;print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
  local maj min; maj="${v%%.*}"; min="${v##*.}"
  if [ "$maj" -lt 3 ] || { [ "$maj" -eq 3 ] && [ "$min" -lt 11 ]; }; then
    c_red "python3 $v found — need >= 3.11 for tomllib."
    return 1
  fi
  c_grn "python3 $v ok"
}

# Tier 1: a `smoke-alarm` command on PATH so ANY agent can run the instruments inside
# any project, with no knowledge of where the tool is installed. Dispatches to the
# instrument scripts by subcommand.
install_cli() {
  rm -rf "${LIB:?}"
  mkdir -p "$LIB" "$BIN_DIR"
  cp -r "$SRC/." "$LIB/"
  cat > "$BIN" <<EOF
#!/usr/bin/env bash
# smoke-alarm launcher (generated by install.sh) — dispatch to the canonical install.
set -euo pipefail
SCRIPTS="$LIB/scripts"
cmd="\${1:-}"; [ \$# -gt 0 ] && shift || true
case "\$cmd" in
  grade|mutate|provenance|audit|gate)
    exec python3 "\$SCRIPTS/\$cmd.py" "\$@" ;;
  ""|-h|--help|help)
    echo "smoke-alarm — interrogate your tests' oracles. Usage:"
    echo "  smoke-alarm grade <path>        static oracle triage (W1-S3)"
    echo "  smoke-alarm audit <path>        grade + provenance, write baseline"
    echo "  smoke-alarm provenance <path>   flag values that may come from the impl"
    echo "  smoke-alarm mutate [args]       run/parse mutation testing"
    echo "  smoke-alarm gate --base <ref>   gate new/changed test files in a diff"
    [ "\$cmd" = "" ] && exit 2 || exit 0 ;;
  *)
    echo "smoke-alarm: unknown command '\$cmd'" >&2
    echo "commands: grade audit provenance mutate gate" >&2; exit 2 ;;
esac
EOF
  chmod +x "$BIN"
  c_grn "installed CLI -> $BIN"
  if ! command -v smoke-alarm >/dev/null 2>&1; then
    c_red "  note: $BIN_DIR is not on your PATH — add it so agents can call 'smoke-alarm':"
    c_dim "    export PATH=\"\$HOME/.local/bin:\$PATH\""
  fi
}

do_install() {
  [ -d "$SRC" ] || { c_red "source not found: $SRC"; exit 1; }
  check_python || c_red "(installing anyway, but the instruments will not run until Python >= 3.11 is available)"
  echo; c_dim "installing CLI (universal entry point for any agent)..."
  install_cli
  echo; c_dim "installing skill files into present AI tools..."
  local installed=0
  for root in "${TOOL_ROOTS[@]}"; do
    if [ -d "$root" ]; then
      rm -rf "${root:?}/$SKILL"
      cp -r "$SRC" "$root/$SKILL"
      c_grn "installed -> $root/$SKILL"
      installed=$((installed + 1))
    else
      c_dim "skip (not present) -> $root"
    fi
  done
  [ "$installed" -gt 0 ] || c_dim "no AI tool skill roots found (CLI still installed and usable)."
  echo
  c_dim "registering auto-grade hook (so the agent checks its own tests, no manual run)..."
  python3 "$SRC/hooks/register_hooks.py" install || c_red "hook registration failed (skill still works via 'smoke-alarm grade <file>')"
  echo
  c_grn "done. restart your tool session so it reloads the skill + hook."
  echo
  c_dim "quick-start (works in any project, any agent):"
  c_dim "  smoke-alarm grade <test-file-or-dir>   # static oracle triage"
  c_dim "  smoke-alarm audit <dir>                # full audit + plan"
}

do_uninstall() {
  # deregister the hook first, while the script is still on disk
  if command -v python3 >/dev/null 2>&1 && [ -f "$SRC/hooks/register_hooks.py" ]; then
    python3 "$SRC/hooks/register_hooks.py" uninstall || true
  fi
  local removed=0
  for root in "${TOOL_ROOTS[@]}"; do
    if [ -d "$root/$SKILL" ]; then
      rm -rf "${root:?}/$SKILL"
      c_grn "removed -> $root/$SKILL"
      removed=$((removed + 1))
    fi
  done
  if [ -f "$BIN" ]; then rm -f "$BIN"; c_grn "removed CLI -> $BIN"; removed=$((removed + 1)); fi
  if [ -d "$LIB" ]; then rm -rf "${LIB:?}"; c_grn "removed lib -> $LIB"; removed=$((removed + 1)); fi
  [ "$removed" -gt 0 ] || c_dim "nothing to remove."
}

do_doctor() {
  local ok=0
  check_python || ok=1
  echo; c_dim "CLI status:"
  if command -v smoke-alarm >/dev/null 2>&1; then
    c_grn "  'smoke-alarm' on PATH -> $(command -v smoke-alarm)"
  elif [ -f "$BIN" ]; then
    c_red "  CLI installed at $BIN but $BIN_DIR is not on PATH"
    c_dim "    add: export PATH=\"\$HOME/.local/bin:\$PATH\""; ok=1
  else
    c_dim "  CLI not installed (run ./install.sh)"
  fi
  echo
  for root in "${TOOL_ROOTS[@]}"; do
    if [ -d "$root" ]; then
      if [ -f "$root/$SKILL/SKILL.md" ]; then
        c_grn "installed: $root/$SKILL"
      else
        c_dim "tool present, skill NOT installed: $root"
      fi
    fi
  done
  echo; c_dim "auto-grade hook status:"
  for cfg in "$HOME/.claude/settings.json" "$HOME/.codex/hooks.json"; do
    if [ -f "$cfg" ] && grep -q "smoke-alarm/hooks/posttooluse.py" "$cfg" 2>/dev/null; then
      c_grn "  hook registered in $cfg"
    elif [ -f "$cfg" ]; then
      c_dim "  hook NOT registered in $cfg (run ./install.sh)"
    fi
  done

  if command -v python3 >/dev/null 2>&1; then
    echo; c_dim "running instrument self-tests..."
    if python3 "$SRC/tests/test_grade.py" >/dev/null 2>&1 \
       && python3 "$SRC/tests/test_ast_grade.py" >/dev/null 2>&1 \
       && python3 "$SRC/tests/test_provenance.py" >/dev/null 2>&1 \
       && python3 "$SRC/tests/test_mutate.py" >/dev/null 2>&1; then
      c_grn "self-tests pass (grade + AST grade + provenance + mutate parsers)"
    else
      c_red "self-tests FAILED — run them individually under $SRC/tests/"; ok=1
    fi
  fi
  return $ok
}

case "${1:-install}" in
  install)   do_install ;;
  uninstall) do_uninstall ;;
  doctor)    do_doctor ;;
  *) echo "usage: $0 [install|doctor|uninstall]"; exit 2 ;;
esac
